@startuml

interface MatcherFieldSpec { 
    Stream<FieldValue> getFieldValues(document)
}
note right of MatcherFieldSpec
    Interface to load field values
end note

class FieldNameMatcherFieldSpec implements MatcherFieldSpec {
    - String fieldName
    + FieldNameMatcherFieldSpec(fieldName)
    + Stream<FieldValue> getFieldValues(document)
}
note right of FieldNameMatcherFieldSpec
    Simple class to return field values in a document
end note
@enduml