@startuml
pst-->email : contains
note left : pst: {tag:WORKBOOK_1, sources:{ image}}
email->word_doc : contains
note left : email: {tag:WORKBOOK_1, sources:{ image}}
word_doc->spreadsheet : contains
note left : word_doc: {tag:WORKBOOK_1, sources:{image}}
word_doc->image : contains
note left: spreadsheet: tag removed
note right: image: {tag:WORKBOOK_1, sources:{image}}
@enduml